### PR TITLE
Add sendDocument and sendPhoto commands. Allows URLs to be used too!

### PR DESCRIPTION
**Pull request by jonnywilliamson**

### CODE REVIEW

**Comment by jonnywilliamson** [comment]
@zyberspace Just wondering if you managed to take a look at this yet?

I am purplexed with one aspect of your code. Perhaps its simple but I don't get it. You have two main classes, 
AbstractClientCommands.php
Client.php

The Client extends Abstract....so far so good I understand. 

However, in your code, methods in the Abstract class, call methods in the Client class. The Abstract class can never know that it will be extended by Client and so there is no way it can be sure it can call methods like escapePeer or escapeStringArgument etc.

The Abstract class knows too much! I don't think this is the correct way to do things.

The Abstact Class should deal with all the connection things, the client class (probably should be called commandsClass) should then extend the Abstract class and provide an API for all the commands that we can call telegram-cli with.

I created a new branch and switched these classes around. I think it makes much more sense (just the class names may need tweaked).

I done lots of testing today and have added nearly every command available to us with telegram-cli. I'm going to merge it into my master.

What do you think?

**Comment by zyberspace** [comment]
Hi @jonnywilliamson, first of all, thx for the pull-request, not everyone does this and yeah, i saw your pull-request, i get a mail for every pull-request on projects that i maintain. ;)
The problem is, that i'm really busy with work at the moment and i don't want to merge code just from a simple overlook.

Talking about the abstract class:

``` php
//This class should actually be a trait and not abstract, but this way we can support PHP 5.3 and
//don't rely on PHP 5.4
```

You are right that the `AbstractClientCommands`-Class is actually wrong and i think i will change it into a trait soon.
But like the description of the class says, it is just meant for command wrappers (aka easier `exec()`-calls).

I think i will have the time to take a deeper look (and change some things) at your code in the next week, work should get less in the next days.

And before you ask, what changes: Just moving some methods around, so the `AbstractClientCommands` will be still a command-wrapper.

**Comment by jonnywilliamson** [comment]
@zyberspace 

Hi! Thanks for getting back to me.

I've been continuing to add to your Wrapper. I think I have most of the commands now added in, (except commands that download/view media attachments).

I had already switched the contents of the files around (although I haven't changed their names yet - but that needs to be done) back in commit https://github.com/jonnywilliamson/php-telegram-cli-client/commit/39029c0091a5b3d61a32fd0257362e2666a67a32

I appreciate that it takes time to get back to these projects - goodness knows how many times that happens to me. I hope that soon however you will be able to review my code and (please modify if necessary) merge.

I would like to release a Laravel Package soon that would require your project but if that all fails I can always publishing my own....it's just I don't like duplicating code!

Thanks again - hopefully speak soon.

**Comment by jonnywilliamson** [comment]
@zyberspace - hi. Any joy in finding some time to have a look at the PR?

**Comment by zyberspace** [comment]
Hi, i will do some code changes by myself first and then cherry-pick from your pull-request. I can not merge the crappy code you produced (based on my crappy oop-usage :D ).
So let me pls tidy up my own mess and then i will see how much code i can use from you (will use the @author tag on your methods, so you still get the credit :) )

**Comment by jonnywilliamson** [comment]
Its ok. 

I've [forked and made my own repository](https://github.com/jonnywilliamson/laragram). Thanks for the start to the project. You don't have to worry about the author tag, just wanted to get the project to work for me.

**Comment by jonnywilliamson** [comment]
If you need/want author tags on your methods please let me know.

**Comment by zyberspace** [comment]
no problem, forks are well appreciated, that's why it is under MPL. Also pull-requests, but i had no time to merge it (you changed way to much structure), even i already had read all your code changes a long time ago.

After my code changes you should also be able to just extend my classes for your laravel-plugin (will do some changes to the code structure, so the core and the command wrappers will be better splitted).

**Comment by jonnywilliamson** [comment]
I'll close this pull request, I updated my documentation to include link here etc.

Thank you.

**Comment by zyberspace** [comment]
Perfect :+1:

**Pull request closed without merging**
